---
title: "Review of COVID-19 Dashboards"
author: "Randi Shashikala"
date: "10/4/2021"
output: pdf_document
---


# 1. Abstract

There are 221 countries & territories which are affected by the COVID-19 global pandemic as the 20th of September 2021. To visualize the COVID-19 data & inform the public, dashboards are the most commonly used visualization tool. The main objective of this study is to identify different features, visualization methods & improvements that should be occurred by exploring the existing dashboards. 15 different dashboards that have been developed to visualize the COVID-19 data for different countries & globally has been explored here. Bar charts, line charts & Interactive maps are the most frequently used visualization tools in developing the dashboards. Dashboards that are fitted on a single screen is better than others.

**Key words** : COVID-19, Dashboard, Visualization

# 2. Introduction

The COVID-19 pandemic is the ongoing global pandemic of coronavirus disease 2019
caused by the Severe Acute Respiratory Syndrome Coronavirus 2 (SARS-CoV-2) virus. The first
patient infected with COVID-19 was identified in Wuhan, China, in December 2019. There have been reported 229835231 confirmed cases, 206515718 recovered cases, 18605877 active cases & 4713636 deaths in global as of 20th September 2021 according to the Worldmeter records. Currently, 99.5% of active patients are mild condition and 0.5% of patients are in critical situation.

Dashboards are one of the best visual interpretation method of tracking the spread & communication of COVID-19 pandemic. There are so many COVID-19 visualization dashboards that have been created to visualize the global & the local situation of the pandemic. Dashboards can be created using different software. There have been explored 15 dashboards which are developed to visualize the COVID-19 data in global & countries. In this paper has been compared dashboards to identify the different features, visualization methods & improvements that should be occurred. 

### 2.1 Data represent in the Dashboards

Initially dashboards have been compared with the type of data to get an idea about which type of data is most frequently visualized in the dashboards.
The dashboards are labeled as follows;

**Table 01: Labeled of the Dashboards**

|No |Name of the Dashboard|
|:--:|:-------------------|
|1 | COVID-19 dashboard created by the John Hopkins University Center for Systems Science & Engineering (JHU CSSE) 
|2 | WHO  COVID-19 Dashboard 
|3 | COVID-19 surveillance dashboard created by the University of Virginia 
|4 | Corona cases (COVID-19) per municipality in Belgium dashboard 
|5 | COVID-19 dashboard for England created by NHS providers 
|6 | NZ COVID-19 Dashboard 
|7 | Pakistan’s official COVID-19 dashboard 
|8 | COVID-19 Canada live dashboard
|9 | India (COVID-19) Dashboard  
|10 | Italy COVID-19 dashboard 
|11 | Jamaica COVID-19 Dashboard 
|12 | GCI COVID-19 dashboard for Russia 
|13 | COVID-19 live situation analysis dashboard of Sri Lanka
|14 | COVID 19 ZA South Africa Dashboard 
|15 | COVID-19 dashboard for German 

**Table 02: Summary of data represent in the dashboards**


| Name of the Dashboard| Location (Represented) | Confirmed Cases| Recovered Cases| Deaths | Vaccination Details| Tests| Global Comparison|
|:------------:|:------------|:------------:|:------------:|:------------:| :------------:|:------------:|:------------:|  
| 1                     | Global | \checkmark        |   \checkmark       |\checkmark  | \checkmark             |   | \checkmark 
| 2                     | Global |\checkmark        |   \checkmark        |\checkmark  | \checkmark              |   | \checkmark 
| 3                     | Global  |   \checkmark        |\checkmark  | \checkmark              |   | \checkmark 
| 4                     | Belgium |\checkmark          |   \checkmark        |\checkmark  |                     |  |  
| 5                     | England |\checkmark          | \checkmark        |\checkmark  | \checkmark              |  |
| 6                     | New Zealand | \checkmark          |   \checkmark       |\checkmark |                     |  |\checkmark 
| 7                     | Pakistan | \checkmark         |  \checkmark        |\checkmark  |                     |\checkmark  |
| 8                     | Canada | \checkmark          |  \checkmark        |\checkmark  |                     |  | |
| 9                     | India | \checkmark         |   \checkmark        |\checkmark  | \checkmark              | | \checkmark 
| 10                    | Italy | \checkmark         |   \checkmark        |\checkmark  |                     |\checkmark  |
| 11                    | Jamaica | \checkmark        |   \checkmark        |\checkmark  | \checkmark            | | 
| 12                    | Russia |\checkmark         |  \checkmark       |\checkmark  |                     | | 
| 13                    | Sri Lanka |\checkmark          |   \checkmark       |\checkmark  |                     | \checkmark  | \checkmark 
| 14                    | South Africa |\checkmark        |   \checkmark        |\checkmark  | \checkmark              | \checkmark  |
| 15                    | German |\checkmark          |  \checkmark        |\checkmark  | \checkmark              | |


As shown in table 02 all dashboards which are considered in this paper represent the data related to COVID-19 confirmed cases, recovered cases & deaths. There have been contained vaccination details, 8 dashboards out of 15 dashboards. In almost each & every dashboard, value boxes have been used to represent these total figures. Bar charts & line charts (trend lines) are most frequently used to visualize these data (confirmed cases, recovered cases, deaths & vaccination details) with respect to time. A Majority of dashboards presented data by daily or weekly. The mapping is used to track the spatial distribution of COVID-19 cases by country/ provincial/ regional etc. When visualizing the data by map color code system & circles with respect to the size of the cases have been used to visualize the variation in size. The considerable number of dashboards has been used doughnut shape pie charts to represent total COVID-19 confirmed cases, recovered cases, active cases & deaths as a percentage. Also, region, gender, age group & ethnicity can be identified as common breakdowns of COVID-19 cases. In some dashboard has been added data tables for representing cases distribution by province/region.  Only very few dashboards have been visualized in COVID-19 test details. Only 6 dashboards have been compared to global situations. In addition, fatality rate, incidence rate, ICU beds, stage of the patients & hospitalize details have been contained in the several dashboards. These are the most common data types that have been contained in the dashboards. The main tools that have been used for different purpose can be shown in the following table.\hfill\break


**Table 03: Summary of tools which are used for different purpose**


|Purpose | Bar chart | Line chart | Pie chart | Dot plot| Heat map| Mapping| Data table|
|:-------|:---------:|:----------:|:---------:|:--------:|:--------:|:-------:|:-------:|
| COVID-19 confirmed 
cases | \checkmark  | \checkmark  |  | \checkmark  |  | \checkmark  |\checkmark 
| COVID-19 deaths | \checkmark  | \checkmark  |  |  | | \checkmark  | \checkmark 
| COVID-19 recovered 
cases | \checkmark  | \checkmark  | | | | \checkmark  | \checkmark
| COVID-19 vaccination | | \checkmark  |  | | | \checkmark  | \checkmark
| COVID-19 test 
conducted | \checkmark  | \checkmark  | | | | |
| Clinical status | \checkmark  | | | | | | 
| Cases distribution by 
age  | \checkmark  | | \checkmark  | | |  |
| Cases distribution by 
gender | \checkmark  | | | | | |
| Cases distribution by area
(Province/state/region) | \checkmark  | \checkmark  |  | | \checkmark  | \checkmark  | \checkmark
| To compare the cases | | |  \checkmark  | | |  |  \checkmark 
| Global comparison |  \checkmark  |  \checkmark  | | | |  \checkmark  | \checkmark 



### 2.2 Comparison of Dashboards

Before developing a dashboard, it is necessary to think about which visualization tools & features that should be contained in the dashboards. What are the most suitable plots, how many panels in the dashboard, what data should be included, how to fit dashboard on a screen, colors & is it real time updated or not are the common things that should be considered before develop the dashboards. In table 02 has been compared these visualization tools & features under the following categories. 

  * Number of panels - How many panels which are included in the dashboard.
  * Visualization tools – what are the graphical representations of data which are contained in the dashboards. 
  * Fitted on a single screen – whether the dashboard fits on a single screen or not (users can see the whole dashboard on a single screen without adjusting through grid overlay or not).
  * Color theme – is there a unique color used for one data type in the whole dashboard (i.e.: one color scale for one data type everywhere on the dashboard). 
  * Dark background – background color of the dashboard is dark or light.
  * Data available – whether users can be downloaded/available the data set which has been visualized on the dashboard. 
  * Real time updated – whether the dashboard is updated daily/ specific time (live dashboard) or not.
  
\hfill\break  
\hfill\break  
\hfill\break  
\hfill\break \hfill\break  
\hfill\break  
\hfill\break  
\hfill\break 
\hfill\break  
\hfill\break  
\hfill\break  
\hfill\break 


**Table 04: Comparison of visualization tools & features of dashboard** 


| Name of the Dashboard | Number of panels|  Visualization tools | Fitted on a single screen | Color theme | Dark background | Data available | Real time updated|
|:-------: |:-------: |:-------:  |:-------:|:-------:   |:-------:  |:-------:   |:-------:  |
| 1                |  1   | Bar chart\hfill\break  Interactive map\hfill\break |\checkmark         |   \checkmark      |\checkmark | \checkmark   | \checkmark
| 2             | 4   | Line chart\hfill\break  Interactive map\hfill\break  Data table\hfill\break|         |   \checkmark       |    |     \checkmark        |\checkmark 
| 3         |2         |Line chart\hfill\break  Bar chart\hfill\break Interactive map\hfill\break Data table\hfill\break  | \checkmark         |   \checkmark       |\checkmark | \checkmark             |\checkmark
|4 | 1|Line chart\hfill\break Bar chart\hfill\break  Pie chart\hfill\break Interactive map\hfill\break |\checkmark |   | \checkmark |\checkmark| \checkmark
|5 | 1| Line chart\hfill\break Bar chart\hfill\break Data table\hfill\break |   | \checkmark |   | \checkmark | \checkmark
|6 | 5| Line chart\hfill\break Bar chart\hfill\break Dot plot\hfill\break  Interactive country map\hfill\break |   |   |   | \checkmark | \checkmark
|7 | 1|  Line chart\hfill\break Bar chart\hfill\break  Country map\hfill\break Data table\hfill\break |    | \checkmark  |    |    | \checkmark
|8 | 3| Line chart\hfill\break Bar chart\hfill\break Data table\hfill\break Interactive map\hfill\break |    |    | \checkmark |   | \checkmark
|9 |3 | Line chart\hfill\break Bar chart\hfill\break Doughnut shape pie chart\hfill\break Data table\hfill\break Interactive country map\hfill\break |  | \checkmark |  | \checkmark | \checkmark 
|10  | 2| Bar chart\hfill\break Doughnut shape pie chart\hfill\break Heat map\hfill\break Interactive country map\hfill\break |   |   |    |    | \checkmark
|11 | 1| Line chart\hfill\break Bar chart\hfill\break Doughnut shape pie chart\hfill\break Data table\hfill\break Interactive country map\hfill\break |  | \checkmark |   |   | \checkmark
|12 | 1| Line chart\hfill\break Bar chart\hfill\break  Interactive map\hfill\break |   | \checkmark | \checkmark |   | \checkmark
|13 | 1| Line chart\hfill\break Bar chart\hfill\break Doughnut shape pie chart\hfill\break |  |\checkmark |   |   | \checkmark
|14| 2| Line chart\hfill\break Bar chart\hfill\break  Interactive Country map\hfill\break |  | \checkmark|   | \checkmark | \checkmark
|15 | 1| Line chart\hfill\break Bar chart\hfill\break  Data table\hfill\break Interactive map\hfill\break | \checkmark| \checkmark| \checkmark|  | \checkmark


  


As shown in table 04 almost each & every dashboard, line charts & bar charts have been used to visualize the data. Heat map & dot plot has been used only one dashboard. Only four dashboards have been fitted with a single screen. The majority of dashboards have used color theme on the whole dashboard. That is, dashboards have been applied different colors for different type of data (i.e. One specific color for confirmed cases, another color for deaths, etc.) in the whole dashboard. The data set & related links have available on some dashboards & users can download these data sets. There are 6 dashboards with dark background while others have been used light background. Last updated time & date of the latest available data  has been reported at the top or bottom of the first panel in the dashboard. Like, half of dashboards included all data in one panel.    


# 3. Conclusions & Discussion

Bar charts & line charts are the most frequently used tools for the visualization of total cases, daily cases & comparisons with respect to time. Some dashboards contained doughnut shape pie charts to summarize the total figures. In almost each and every dashboard, value boxes have been used to represent total figures. Some dashboards contained interactive maps & data tables to visualize the distribution of cases by country, province, region or state. All dashboards are daily updating real time dashboards. Gender, age groups and ethnicity can be identified as common breakdowns. The data sets & related links are available on most of the dashboards & can be downloaded. It can be seen that it is very easy, clear and user friendly to identify confirmed, recovered and deceased cases in dashboards which include one color theme for the whole dashboard. Dashboards with the dark background are more comfortable to the eyes than dashboards with light background & light colors. Also, it is better if the dashboard can be fitted on a single screen rather than adjusting through a grid overlay.

# 4. References

[1] COVID 19 Dashboard India – ZOHO Analytics – ZOHO, viewed 01 September 2021,
https://www.zoho.com/covid/india/

[2] COVID-19 dashboard – NHS providers, viewed 31 August 2021,
https://nhsproviders.org/topics/covid-19/tracking-covid-19-data/covid-19-dashboard

[3] COVID-19 in Belgium – Dashboard, viewed 31 August 2021,https://esribelux.maps.arcgis.com/apps/opsdashboard/index.html#/e350724c87af49bb9ce29646f8a42344

[4] COVID-19 integrated surveillance data in Italy – EpiCentro, viewed 02 September 2021,
https://www.epicentro.iss.it/en/coronavirus/sars-cov-2-dashboard

[5] COVID-19: Live situational Analysis Dashboard of Sri Lanka, viewed 08 September 2021,
https://hpb.health.gov.lk/covid19-dashboard/

[6] COVID-19 Map – Johns Hopkins Coronavirus Resource Center, viewed 31 August 2021,
https://coronavirus.jhu.edu/map.html

[7] COVID-19 Surveillance Dashboard – NSSAC Research, viewed 08 September 2021,
https://nssac.bii.virginia.edu/covid-19/dashboard/

[8] COVID 19 ZA Dashboard – Data Studio, viewed 08 September 2021,
https://datastudio.google.com/u/0/reporting/1b60bdc7-bec7-44c9-ba29-be0e043d8534/page/hrUIB

[9] Ministry of Health and Wellness, viewed 02 September 2021, https://jamcovid19.moh.gov.jm/

[10] New Zealand COVID-19 Surveillance Dashboard, viewed 27 August 2021,
https://nzcoviddashboard.esr.cri.nz/#!/

[11] Pakistan’s Official COVID-19 Dashboard – Shifa International Hospitals Ltd, viewed 01
September 2021, https://www.shifa.com.pk/covid-19-pakistan/

[12] RKI COVID-19 Germany – ArcGIS Experience, viewed 08 September 2021,
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

[13] The Global COVId-19 Index (GCI) – Russia Dashboard – PEMANDU Associates, viewed
31 August 2021, https://covid19.pemandu.org/Russia

[14] Track COVID-19 Across Canada Using Our Interactive Dashboards, viewed 01 September
2021, https://samples.dundas.com/Dashboard/62cef916-5488-4d3b-9c57-204092d01813?e=false&vo=viewonly

[15] WHO Coronavirus (COVID-19) Dashboard, viewed 01 September 2021,
https://covid19.who.int/?gclid=CjwKCAjwvuGJBhB1EiwACU1Aia9pAaNLOkBMS2KVlSqXptskt1t46b7_bNv6vpTt_HjvXfrnDS-rWxoCE3sQAvD_BwE

