---
title: "Dashboard Panel Description"
author: "Randi Shashikala"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The "Sri Lanka COVID-19 Dashboard" provides an overview of the COVID-19 pandemic for Sri Lanka. This dashboard has eight panels as follows.

**Table 01: Description of the panels**

| **Name of the Panel**|**Description of the Panel**| 
|:------|:----------------------------------------------|
|Overview          |Total count of COVID-19 confirmed, recovered, deaths, active cases & total vaccine doses administered.\hfill\break Provide an overview of daily COVID-19 confirmed, recovered & deaths by plots.\hfill\break|
|Cases by Wave| There are three tabs in this panel.\hfill\break  * Total COVID-19 confirmed cases - Cumulative count of COVID-19 confirmed cases with specific dates\hfill\break * COVID-19 Cases Distribution by Wave - Daily confirmed cases by wave\hfill\break * COVID-19 Deaths Distribution by Wave - Daily deaths by wave\hfill\break| 
|COVID-19 Patients Distribution | Provide an overview of confirmed cases district wise distribution. There are four tabs in this panel.\hfill\break * Total COVID-19 Patients Distribution in Sri Lanka - Total confirmed counts for each district is represented by tree map\hfill\break * Country Map - Total confirmed cases in each district represented by Sri Lanka country map\hfill\break * Distribution of Daily COVID-19 Patients for Last 30 Days - Visualize the daily confirmed cases distribution by districts in last 30 days\hfill\break * By Applying Min-Max Transformation - Visualize the details in the third tab by applying min-max transformation for each district\hfill\break|
|Vaccination Details | Provide an overview of COVID-19 vaccination in Sri Lanka. There are two tabs.\hfill\break * Total Vaccine Doses - Visualize the administered vaccine doses as first dose only & fully vaccinated\hfill\break * Total Administered Doses by Vaccine Name - Visualize the vaccination by vaccine names\hfill\break|
| Top 10 Countries| In this panel, compare the Sri Lanka confirmed & deaths with top 10 countries in the world (top 10 countries - The countries which have been reported highest number of confirmed cases as 31st of August 2021).\hfill\break There are two tabs.\hfill\break * Comparison of Cumulative Cases in Sri Lanka with Top 10 Countries - Compare the confirmed and deaths in Sri Lanka with top 10 countries by cumulative time series plots\hfill\break * Comparison of Log of Cumulative Cases in Sri Lanka with Top 10 Countries -  Compare the confirmed and deaths in Sri Lanka with top 10 countries by log cumulative time series plots\hfill\break (The data has been pulled from WHO)\hfill\break|
|Global Comparison | Compare the total confirmed & deaths in Sri lanka with top 10 countries in Global & Asia. There are two tabs.\hfill\break * Comparison of the sri Lanka with Top 10 Countries Reporting the Most COVID-19 Cases in the World - Compare the total confirmed & deaths in Sri Lanka with top 10 countries in the world & compare the case fatality ratios\hfill\break * Comparison of the sri Lanka with Top 10 Countries Reporting the Most COVID-19 Cases in the Asia - Compare the total confirmed & deaths in Sri Lanka with top 10 countries in the Asia & compare the case fatality ratios\hfill\break|
|Global Map| Visualize the distribution of confirmed, recovered & deaths in the world by world map.\hfill\break|
|About | This panel contains the details about the dashboard.|

